### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [n-t-roff/vddiff#1]
[Extra null pointer checks are not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [the function “dl_list”](https://github.com/n-t-roff/vddiff/blob/5662b621af5f0cdb110468eddf1bab9ca2b7cbf6/dl.c#L390 "Update candidate: dl_list()").

**Comment by n-t-roff** [comment]
This had been a questionable optimization to save a function call. The intent was to save the time for the function call since the if statement is executed much faster. I had been aware that free does this check anyway.

**Comment by elfring** [comment]
* Do you care for the concrete occurrence frequency of null pointers at these two source code places?
* Are valid pointers usually more likely there?

**Comment by n-t-roff** [comment]
That's not the point. I wanted to avoid an expensive function call with a cheap integer compare. But this instruction is reached seldom so the expensive function call does not effect run time. But the `if` statement (while not necessary) does not hurt too.

**Comment by elfring** [comment]
I dare to propose the reconsideration of redundant condition checks.
Can the code size occasionally have an desirable influence here?

**Comment by n-t-roff** [comment]
Won't fix (although reasonable)
