### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [n-t-roff/vddiff#2]
* The function “[printerr](https://github.com/n-t-roff/vddiff/blob/9a0681e83a44b55057476d8ad326cca0011966c2/ui.c#L4247)” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
  I guess that a different program design will be needed for your function “[sig_child](https://github.com/n-t-roff/vddiff/blob/5662b621af5f0cdb110468eddf1bab9ca2b7cbf6/exec.c#L796 "Update candidate")”.
* The function “sig_term” should be implemented somehow, shouldn't it?

**Comment by n-t-roff** [comment]
`sig_term` is defined in `main.c`. There are a lot of dangerous function called in `sig_term`. I have to analyse this and check if the alternatives you mentioned for `sc` are applicable.

**Comment by n-t-roff** [comment]
Done
