### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [n-t-roff/vddiff#3]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [db_new](https://github.com/n-t-roff/vddiff/blob/3397b65745f0203f512927ab663781167ad55d3a/db.c#L132)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [hist_add](https://github.com/n-t-roff/vddiff/blob/5662b621af5f0cdb110468eddf1bab9ca2b7cbf6/ed.c#L229)

**Comment by n-t-roff** [comment]
This is quite some work. It will be addressed in the long term.

**Comment by elfring** [comment]
Can higher level development tools help you to complete the corresponding exception handling?

**Comment by n-t-roff** [comment]
Which tools did you use to find the issues?

**Comment by elfring** [comment]
The GitHub source code search (for example) can find such update candidates.

**Comment by n-t-roff** [comment]
I don't know this feature.
I mean what tools did you use to analyse the source code to find coding style issues which needs improvement?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by n-t-roff** [comment]
> How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B) also for this software?

Exactly which static code analysis tools are you using--especially for C++?

> * Are you interested to apply [aspect-oriented software development](https://aspectc.org/)?

I'll have a look at it.

> * Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in this software?

I use C++ for new projects with strong focus on reuse. C++ exception would solve the specific issue anyway.

**Comment by n-t-roff** [comment]
Will be addressed for new code only
